spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate # | update | create | create-drop
      format_sql: true